"""Audit report generation service (FR-24).

Generates structured compliance audit reports in PDF and JSON formats,
containing control statuses, evidence references, and regulatory citations.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone

from jinja2 import Template

PDF_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Compliance Audit Report — {{ project_name }}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
        h1 { color: #1a1a2e; border-bottom: 2px solid #16213e; padding-bottom: 10px; }
        h2 { color: #16213e; margin-top: 30px; }
        h3 { color: #0f3460; }
        .control { border: 1px solid #ddd; padding: 15px; margin: 10px 0; border-radius: 5px; }
        .status-pass { border-left: 4px solid #27ae60; }
        .status-fail { border-left: 4px solid #e74c3c; }
        .status-needsreview { border-left: 4px solid #f39c12; }
        .status-pending { border-left: 4px solid #95a5a6; }
        .badge { padding: 3px 8px; border-radius: 3px; font-size: 12px; font-weight: bold; }
        .badge-pass { background: #27ae60; color: white; }
        .badge-fail { background: #e74c3c; color: white; }
        .badge-needsreview { background: #f39c12; color: white; }
        .citation { color: #666; font-style: italic; margin-top: 5px; }
        .evidence { background: #f8f9fa; padding: 8px; margin: 5px 0; border-radius: 3px; }
        .summary { display: flex; gap: 20px; margin: 20px 0; }
        .summary-card { padding: 15px; border-radius: 8px; flex: 1; text-align: center; }
        .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #666; font-size: 12px; }
    </style>
</head>
<body>
    <h1>Compliance Audit Report</h1>
    <p><strong>Project:</strong> {{ project_name }}</p>
    <p><strong>Generated:</strong> {{ generated_at }}</p>
    <p><strong>Generated by:</strong> {{ generated_by }}</p>
    <div class="summary">
        <div class="summary-card" style="background: #e8f5e9;">
            <div style="font-size: 24px; font-weight: bold;">{{ pass_count }}</div>
            <div>Passed</div>
        </div>
        <div class="summary-card" style="background: #ffebee;">
            <div style="font-size: 24px; font-weight: bold;">{{ fail_count }}</div>
            <div>Failed</div>
        </div>
        <div class="summary-card" style="background: #fff3e0;">
            <div style="font-size: 24px; font-weight: bold;">{{ review_count }}</div>
            <div>Needs Review</div>
        </div>
        <div class="summary-card" style="background: #f3e5f5;">
            <div style="font-size: 24px; font-weight: bold;">{{ evidence_count }}</div>
            <div>Evidence Items</div>
        </div>
    </div>

    {% for framework in frameworks %}
    <h2>{{ framework.name }} (v{{ framework.version }})</h2>

    {% for control in framework.controls %}
    <div class="control status-{{ control.status|lower }}">
        <h3>{{ control.control_id_code }} — {{ control.title }}</h3>
        <span class="badge badge-{{ control.status|lower }}">{{ control.status }}</span>
        <p>{{ control.description }}</p>
        <p class="citation">Citation: {{ control.source_citation }}</p>
        {% for req in control.requirements %}
        <p>• {{ req.description }}</p>
        {% endfor %}
        {% if control.evidence_items %}
        <div style="margin-top: 10px;">
            <strong>Supporting Evidence:</strong>
            {% for ev in control.evidence_items %}
            <div class="evidence">
                <span class="badge">{{ ev.source_type }}</span>
                {{ ev.source_ref }}
                <br><small>Collected: {{ ev.collected_at }} | Hash: {{ ev.sha256_hash }}</small>
            </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    {% endfor %}
    {% endfor %}

    <div class="footer">
        <p>Generated by SentinellAI Compliance Platform</p>
    </div>
</body>
</html>
"""


def generate_json_report(report_data: dict) -> str:
    """Generate a JSON audit report string."""
    report_data["generated_at"] = datetime.now(timezone.utc).isoformat()
    return json.dumps(report_data, indent=2, default=str)


async def generate_pdf_report(report_data: dict) -> bytes:
    """Generate a PDF audit report from the report data.

    Uses WeasyPrint to render an HTML template to PDF.
    """
    all_controls = [
        control
        for framework in report_data.get("frameworks", [])
        for control in framework.get("controls", [])
    ]
    pass_count = sum(1 for control in all_controls if control.get("status") == "Pass")
    fail_count = sum(1 for control in all_controls if control.get("status") == "Fail")
    review_count = sum(
        1 for control in all_controls if control.get("status") == "NeedsReview"
    )
    evidence_count = sum(
        len(control.get("evidence_items", [])) for control in all_controls
    )

    template = Template(PDF_TEMPLATE)
    html = template.render(
        project_name=report_data.get("project", {}).get("name", "Unknown"),
        generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        generated_by=report_data.get("generated_by", "System"),
        frameworks=report_data.get("frameworks", []),
        pass_count=pass_count,
        fail_count=fail_count,
        review_count=review_count,
        evidence_count=evidence_count,
    )

    import typing

    from weasyprint import HTML
    return typing.cast(bytes, HTML(string=html).write_pdf())
