"""evidence_redacted_flag

Revision ID: 03452933d41d
Revises: c04612167a84
Create Date: 2026-05-03 14:02:48.533104
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03452933d41d'
down_revision: Union[str, None] = 'c04612167a84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('controls', 'status',
               existing_type=postgresql.ENUM('Pass', 'Fail', 'NeedsReview', 'Pending', name='control_status_enum'),
               nullable=False,
               existing_server_default=sa.text("'Pending'::control_status_enum"))
    op.drop_index(op.f('ix_controls_embedding'), table_name='controls', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('evidence_items', 'redacted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('frameworks', 'version',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'1.0'::character varying"))
    op.drop_index(op.f('ix_regulatory_chunks_embedding'), table_name='regulatory_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_column('regulatory_chunks', 'embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regulatory_chunks', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_regulatory_chunks_embedding'), 'regulatory_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('frameworks', 'version',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'1.0'::character varying"))
    op.alter_column('evidence_items', 'redacted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_controls_embedding'), 'controls', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('controls', 'status',
               existing_type=postgresql.ENUM('Pass', 'Fail', 'NeedsReview', 'Pending', name='control_status_enum'),
               nullable=True,
               existing_server_default=sa.text("'Pending'::control_status_enum"))
    # ### end Alembic commands ###
