"""OSCAL 1.1.2 Assessment Results Pydantic v2 models."""

from __future__ import annotations

from datetime import datetime
from uuid import UUID, uuid4

from pydantic import BaseModel, ConfigDict, Field


class OSCALBaseModel(BaseModel):
    model_config = ConfigDict(populate_by_name=True)


class OSCALMetadata(OSCALBaseModel):
    title: str
    last_modified: datetime = Field(serialization_alias="last-modified")
    version: str = "1.0.0"
    oscal_version: str = Field(default="1.1.2", serialization_alias="oscal-version")


class OSCALProp(OSCALBaseModel):
    """OSCAL property — key/value metadata attached to any element."""

    name: str
    value: str
    ns: str = "https://sentinellai.dev/ns/oscal"


class OSCALSubjectReference(OSCALBaseModel):
    subject_uuid: UUID = Field(serialization_alias="subject-uuid")
    type: str
    title: str | None = None


class OSCALObservation(OSCALBaseModel):
    """Maps to an EvidenceItem in SentinellAI."""

    uuid: UUID = Field(default_factory=uuid4)
    title: str
    description: str
    collected: datetime
    methods: list[str] = Field(default_factory=lambda: ["AUTOMATED"])
    types: list[str] = Field(default_factory=lambda: ["finding"])
    props: list[OSCALProp] = Field(default_factory=list)


class OSCALRelatedObservation(OSCALBaseModel):
    observation_uuid: UUID = Field(serialization_alias="observation-uuid")


class OSCALTargetStatus(OSCALBaseModel):
    state: str
    reason: str | None = None


class OSCALFindingTarget(OSCALBaseModel):
    type: str = "objective-id"
    target_id: str = Field(serialization_alias="target-id")
    status: OSCALTargetStatus


class OSCALRelatedRisk(OSCALBaseModel):
    risk_uuid: UUID = Field(serialization_alias="risk-uuid")


class OSCALFinding(OSCALBaseModel):
    """Maps to a Control evaluation result in SentinellAI."""

    uuid: UUID = Field(default_factory=uuid4)
    title: str
    description: str
    target: OSCALFindingTarget
    related_observations: list[OSCALRelatedObservation] = Field(
        default_factory=list, serialization_alias="related-observations"
    )
    related_risks: list[OSCALRelatedRisk] = Field(
        default_factory=list, serialization_alias="related-risks"
    )


class OSCALRisk(OSCALBaseModel):
    uuid: UUID = Field(default_factory=uuid4)
    title: str
    description: str
    status: str = "open"
    characterizations: list[OSCALProp] = Field(default_factory=list)


class OSCALResult(OSCALBaseModel):
    """One result per framework evaluation run."""

    uuid: UUID = Field(default_factory=uuid4)
    title: str
    description: str
    start: datetime
    end: datetime | None = None
    findings: list[OSCALFinding] = Field(default_factory=list)
    observations: list[OSCALObservation] = Field(default_factory=list)
    risks: list[OSCALRisk] = Field(default_factory=list)
    props: list[OSCALProp] = Field(default_factory=list)


class OSCALAssessmentResults(OSCALBaseModel):
    """OSCAL Assessment Results document root payload."""

    uuid: UUID = Field(default_factory=uuid4)
    metadata: OSCALMetadata
    results: list[OSCALResult]

    model_config = ConfigDict(
        populate_by_name=True,
        json_schema_extra={
            "description": "OSCAL 1.1.2 Assessment Results generated by SentinellAI"
        },
    )
